### ISSUE TITLE
ISP fallback

### ISSUE THREAD

**Issue by fredbcode** [lstein/Net-ISP-Balance#10]
Hello,

I think that I saw a problem, when an ISP is come back Net-ISP-Balance still down
The reason seems logic, the default gateway for the "bad" ISP is gone so the ping still KO forever

OK:
0.0.0.0         192.168.8.1     0.0.0.0         UG    203    0        0 eth1
0.0.0.0         192.168.3.1     0.0.0.0         UG    204    0        0 usb0

The second KO:
0.0.0.0         192.168.8.1     0.0.0.0         UG    203    0        0 eth1

And If I restore the default route manually Net-ISP-Balance is happy and usb0 works again
Of course, I can use a local ping-ip (no gateway needed) but it's very limited ...

**Comment by rabchev** [comment]
I can confirm the issue. If a connection to ISP is lost for a while, load_balance.pl does not restore it automatically when it is available again. 

Otherwise, excellent job, thank you very much.

**Comment by lstein** [comment]
Ok, I thought I had fixed this in version 1.18 but apparently not. I made a number of changes in version 1.20, just released, which did not directly address this problem but were designed to be more proactive with respect to identifying changed interface configurations. I will investigate, but if you don't mind trying version 1.20 on your system I would be obliged.

**Comment by rabchev** [comment]
Actually, my primary connection did recover automatically yesterday, but it took quite a while. I din't have time to investigate. Yesterday the primary connection dropped when I was away, when I got back in a few hours the primary connection was up and running properly again. I will have to experiment a bit more to see what is happening.   

I have another question for you though. What is required to make the mail notifications work? You mention about "mail" program as dependency in the documentation.  Can you elaborate on that a bit more? What is that and how is it installed? Sorry if that is a dumb question, but I'm quite unfamiliar with Perl.

**Comment by oblitum** [comment]
Hi, I'm also with @rabchev, I dunno what program exactly is "mail".

**Comment by oblitum** [comment]
Googling, I've found a "mail" program that on Ubuntu for example can be installed with `sudo apt-get install mailutils`. It seems well know but online references point to several others at the same time.

**Comment by oblitum** [comment]
This could be mentioned in docs.

**Comment by christianwedell** [comment]
Hi people! This tool is great! :-)
And I'd like a solution for the routing problem after fallback situation also...

**Comment by lstein** [comment]
I have some potential good news. I made some speculative changes and the
routing-after-fallback problem has not occurred for me since I made the
changes (over a period of three weeks, but the issue only occurs every
month or so). Could you try installing the "development" branch? You can
use GitHub to do this by setting the branch to "development" and then
downloading the ZIP file.

Lincoln

On Sat, Feb 27, 2016 at 8:10 AM, christianw <notifications@github.com>
wrote:

> Hi people! This tool is great! :-)
> And I'd like a solution for the routing problem after fallback situation
> also...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lstein/Net-ISP-Balance/issues/10#issuecomment-189636562>
> .
>



-- 
*Lincoln Stein *
Director, Informatics and Bio-computing Program and Senior Principal
Investigator
Professor, Department of Molecular Genetics, University of Toronto

*Ontario Institute for Cancer Research*
MaRS Centre
661 University Avenue
Suite 510
Toronto, Ontario
Canada M5G 0A3

Tel: 416-673-8514
Mobile: 416-817-8240
Email: lincoln.stein@gmail.com
Toll-free: 1-866-678-6427
Twitter: @OICR_news

*Executive Assistant*
*Frances Dirnbeck*
Tel: 647-259-4253
Email:frances.dirnbeck@oicr.on.ca <stacey.quinn@oicr.on.ca>
www.oicr.on.ca

This message and any attachments may contain confidential and/or privileged
information for the sole use of the intended recipient. Any review or
distribution by anyone other than the person for whom it was originally
intended is strictly prohibited. If you have received this message in
error, please contact the sender and delete all copies. Opinions,
conclusions or other information contained in this message may not be that
of the organization.

**Comment by christianwedell** [comment]
Hi Lincoln,
thanks for keeping us up to date. I will try it as soon as I'm back at this location. But maybe not within 14 days...
Thanks and see you...
Christian

**Comment by lstein** [comment]
I've found and fixed another issue with lsm that would cause it to fail to successfully ping interfaces that have gone down and come back again. Please give version 1.22 (released April 10) a try. Hopefully this is the last such issue, but I am strongly tempted to replace lsm with something simpler and more stable.
