### ISSUE TITLE
Warning message when building

### ISSUE THREAD

**Issue by Polioman** [lstein/Net-ISP-Balance#9]
Hi,

i've got a warning message when building using Build.PL :

    perl ./Build.PL
    WARNING: the following files are missing in your kit:
            META.json
            META.yml
    Please inform the author.

    Created MYMETA.yml and MYMETA.json
    Creating new 'Build' script for 'Net-ISP-Balance' version '1.18'``

Build essential and perl v5.20.2 are installed.

I'm working on a Raspberry PI with Raspbian Jessie if it can help.

it's only a warning and files are created but I was told to infomr the author :)

**Comment by lstein** [comment]
Sorry for the delay in the response! I missed this request due to the christmas holidays.

Thanks for doing what the build script told you to do. You only get these messages when installing from the GitHub source code. If you use the Perl CPAN package, these files are created during the packaging process.  As you correctly concluded, the warnings can be ignored.
